### ISSUE TITLE
Support get monitoring data from NZXT E Series PSU

### ISSUE THREAD

**Issue by yujinlin0224** [NZXTCorp/web-integrations-types#6]
Please support get monitoring data from NZXT E Series PSU.
It would be very useful if PSU's monitoring data can be shown on screen of Kraken.

**Comment by yujinlin0224** [comment]
Any update?

**Comment by RobbiePlata** [comment]
@yujinlin0224 hello, thanks for the feedback, I'll share this with the team

**Comment by robbieplata** [comment]
@yujinlin0224 we'll continue adding more useful data to the API so stay tuned. Thanks.
